checks:
  - signal: "agenda"
    phrases:
      - "decides to include"

  - signal: "Secretariat"
    phrases:
      - "Secretariat"

  - signal: "PGA"
    phrases:
      - "President of the General Assembly"
