patterns:
  - name: "L documents"
    template: "A/{session}/L.{number}"
    session: 80
    start: 1

  - name: "Committee L documents"
    template: "A/C.{committee}/{session}/L.{number}"
    committee: [1, 2, 3, 4, 5, 6]
    session: 80
    start: 1

  - name: "Resolutions"
    template: "A/RES/{session}/{number}"
    session: 80
    start: 1
